name: Release Flyme-GT with Custom Name
on:在:
  release:  发布:
    types: [created]

jobs:工作:
  package_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # 拉取仓库代码

      - name: Package with Version Name
        run: |
          # 获取 Release 版本号（如 v1.0.0）
          VERSION=${{ github.event.release.tag_name }}
          # 假设要打包项目根目录下的所有文件（可根据实际修改打包范围）
          zip -r Flyme_GT_${VERSION}.zip .
          # 若只需打包特定文件/目录，示例：zip -r Flyme_GT_${VERSION}.zip Flyme_gt_module/

      - name: Upload to Release      - name: 上传到发布版本
        uses: softprops/action-gh-release@v1
        with:
          files: Flyme_GT_${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
